---
- name: Install Server Density dependencies (Debian/Ubuntu)
  apt:
    name: curl
    state: present
  when: ansible_os_family == "Debian"

- name: Install Server Density dependencies (RedHat/CentOS)
  yum:
    name: curl
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Server Density agent v2
  include: agent.yml
  when: upgrade_v2 is not defined

- name: Upgrade Server Density agent to v2
  include: upgrade.yml
  when: upgrade_v2 is defined

- name: Configure Server Density agent
  template:
    src: config.template.j2
    dest: /etc/sd-agent/config.cfg
    owner: sd-agent
    group: sd-agent
    mode: 0660
    backup: "{{ backup_configcfg }}"
  notify: restart sd-agent

- name: Install Server Density plugins
  include: plugins.yml
  when: plugins is defined

