---
# Sets your server group
group_name: "ungrouped"

# Optional configuration
plugin_directory: "/usr/local/share/sd-plugins/"

# Log level
log_level: "INFO"

# Delete .example configuration files
delete_example: True

# Ubuntu Default
ansible_lsb:
  id: "ubuntu"
